### PR TITLE
More detail for new people!

### PR DESCRIPTION
**Pull request by nough**
These changes should make onboarding to the safety signs much easier for new people. The readme now gives more detail on how it works, and there is a full template of a machinepage in the safetysheets.tex file.

I have made more usability changes in the Bristol version, but I won't pull request these, as they fit better with Bristol's vibe.

### CODE REVIEW

**Comment by dirkx** [comment]
Thanks for this - rather than accept the pull request with a fair bit of Bristol Lore - I've manually merged things that appears relevant to both our spaces. Am wondering if base.tex should be extended a bit - with a few flags for forum/mail and induction/instruction - so it becomes easier to maintain. And if I should break out each machine in a small, more generic, sign.

B.t.w. the reason why some things appear `overly' mandatory is that for some machines, under the CE mark, having read the instructions ties to the regulatory regimen.

**Comment by dirkx** [comment]
Thanks for this - rather than accept the pull request with a fair bit of Bristol Lore - I've manually merged things that appears relevant to both our spaces. Am wondering if base.tex should be extended a bit - with a few flags for forum/mail and induction/instruction - so it becomes easier to maintain. And if I should break out each machine in a small, more generic, sign.

B.t.w. the reason why some things appear `overly' mandatory is that for some machines, under the CE mark, having read the instructions ties to the regulatory regimen.

**Comment by nough** [comment]
Apologies, I had forgotten that there was still an open pull request in place, and merged my test branch in to my main (which had only things I thought suitable to Leiden). 

Base.tex could probably be both extended and made simpler to understand. That's a project for another year!

**Comment by dirkx** [comment]
No worries & you fixing typo's and dutchisms much appreciated :)

**Pull request closed without merging**
